# Generated by Django 5.2.14 on 2026-05-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('HR Round', 'HR Round'), ('Technical Round', 'Technical Round'), ('Managerial Round', 'Managerial Round'), ('Final Round', 'Final Round')], max_length=100)),
                ('questions', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('preparation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
        ),
    ]
